version: '3.8'
services:
  mysql:
    image: mysql
    container_name: mysql-db
    environment:
        MYSQL_ROOT_PASSWORD: MatKhau123!
    ports:
      - "3100:3306"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql